export const GET_ALL_CATEGORY_SUCCESS = "GET_ALL_CATEGORY_SUCCESS";

export const CURRENT_CATEGORY = "CURRENT_CATEGORY";

export const GET_ALL_PRODUCT_SUCCESS = "GET_ALL_PRODUCT_SUCCESS";

export const SEARCH_PRODUCT = "SEARCH_PRODUCT";

export const LOADING_SCREEN = "LOADING_SCREEN";

export const PRODUCT_DETAIL_SUCCESS = "PRODUCT_DETAIL_SUCCESS";

export const LOGIN = "LOGIN";

export const LOGOUT = "LOGOUT";

export const NOTLOGIN = "NOTLOGIN";

export const NOTLOGOUT = "NOTLOGOUT";

export const USERDATA = "USERDATA";

export const LOG_STATE = "LOG_STATE";

export const PRODUCT_ADD_TO_CART = "PRODUCT_ADD_TO_CART";

export const PRODUCT_REMOVE_FROM_CART = "PRODUCT_REMOVE_FROM_CART";

export const FULL_PRODUCT_REMOVE_FROM_CART = "FULL_PRODUCT_REMOVE_FROM_CART";

export const REGISTER = "REGISTER";

export const LIKE_PRODUCT = "LIKE_PRODUCT";

export const UNDO_LIKE_PRODUCT = "UNDO_LIKE_PRODUCT";

export const FORGOT_PASSWORD = "FORGOT_PASSWORD";

export const RESET_PASSWORD = "RESET_PASSWORD";

export const PROFILE = "PROFILE";

export const IMAGE_UPLOAD = "IMAGE_UPLOAD";

export const PROFILE_IMAGE_STATIC = "PROFILE_IMAGE_STATIC";

export const PROFILE_EDIT = "PROFILE_EDIT";

export const PROFILE_IMAGE_LOCAL = "PROFILE_IMAGE_LOCAL";

export const PRODUCT_ADD = "PRODUCT_ADD";

export const PRODUCT_ADD_IMAGE = "PRODUCT_ADD_IMAGE";

export const PRODUCT_ADD_IMAGE_STATIC = "PRODUCT_ADD_IMAGE_STATIC";

export const PRODUCT_UPDATE = "PRODUCT_UPDATE";

export const PRODUCT_UPDATE_IMAGE = "PRODUCT_UPDATE_IMAGE";

export const GET_USER_CART = "GET_USER_CART";

export const PRODUCT_DELETE = "PRODUCT_DELETE";
