let initialState = {
  categories: [],
  products: [],
  currentCategory: {},
  searchProduct: [],
  loading: false,
  productDetail: {},
  login: {},
  logout: {},
  notLogin: "",
  notLogout: "",
  user: [],
  logState: true,
  carts: [],
  register: {},
  like: {},
  undoLike: {},
  forgotPassword: {},
  resetPassword: {},
  profile: {},
  profileImageUpload: {},
  profileImageStatic: "",
  profileEdit: {},
  profileImageLocal: "",
  productAdd: {},
  productAddImage: [],
  productAddImageStatic: "",
  productUpdate: {},
  productUpdateImage: [],
  getUserCart: [],
  productDelete: {},
};

export default initialState;
